apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ffbb1-dev
  namespace: argocd
  labels:
    app: ffbb1
    environment: dev
    tenant: opsera
spec:
  project: default
  source:
    repoURL: https://github.com/opsera-test-org/february-mail.git
    targetRevision: main
    path: .opsera-ffbb1/k8s/overlays/dev
  destination:
    name: opsera-usw2-np
    namespace: opsera-ffbb1-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
