apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-demo-mail-dev

commonLabels:
  app: demo-mail
  tenant: opsera

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
