apiVersion: v1
kind: Service
metadata:
  name: demo-mail
  namespace: opsera-demo-mail-dev
  labels:
    app: demo-mail
    tenant: opsera
spec:
  type: ClusterIP
  selector:
    app: demo-mail
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
