apiVersion: v1
kind: ConfigMap
metadata:
  name: fbb1-config
  namespace: opsera-fbb1-dev
  labels:
    app: fbb1
    tenant: opsera
    managed-by: opsera-c2c
data:
  APP_NAME: "fbb1"
  ENVIRONMENT: "dev"
  PORT: "8080"
