apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-fbb1-dev

resources:
  - ../../base

labels:
  - includeSelectors: false
    pairs:
      environment: dev
      tenant: opsera

images:
  - name: fbb1
    newName: PLACEHOLDER_ECR_URI
    newTag: latest
