apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-fbb1-dev

resources:
  - ../../base

labels:
  - includeSelectors: false
    pairs:
      environment: dev
      tenant: opsera

images:
  - name: fbb1
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/fbb1
    newTag: dev-0971bfbf-20260212184642
