apiVersion: v1
kind: Service
metadata:
  name: ffbb1
  namespace: opsera-ffbb1-dev
  labels:
    app: ffbb1
    tenant: opsera
spec:
  type: ClusterIP
  selector:
    app: ffbb1
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
