apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-ffbb1-dev

resources:
  - ../../base

images:
  - name: ffbb1
    newName: PLACEHOLDER_ECR_URI
    newTag: latest

labels:
  - includeSelectors: false
    pairs:
      environment: dev
