apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-ffbb1-dev

resources:
- ../../base

images:
- name: ffbb1
  newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/ffbb1

labels:
- pairs:
    environment: dev
