apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fbb1-dev
  namespace: argocd
  labels:
    app: fbb1
    environment: dev
    tenant: opsera
    managed-by: opsera-c2c
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/opsera-test-org/february-mail.git
    targetRevision: main
    path: .opsera-fbb1/k8s/overlays/dev
  destination:
    name: opsera-usw2-np
    namespace: opsera-fbb1-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
